Game level loading
FuzzyNovaGoblin/GrappleGirl pull request #55
Opened 2021-04-14 21:33 UTC by FuzzyNovaGoblin

2021-04-14 23:02 UTC, Redempt requested changes, later dismissed

2021-04-14 23:02 UTC, Redempt commented on GrappleGirlGame/Levels.lua
> +   gGirl.body:setX(level.spawn.x*BLOCK_WIDTH)
Gonna have to update this now that I fixed it in the level editor

2021-04-20 23:58 UTC, liamcannon approved these changes

2021-04-21 00:03 UTC, Redempt approved these changes

2021-04-21 00:04 UTC, merged